[package]
name = "cityrade"
version = "0.1.0"
edition = "2024"
<<<<<<< HEAD
authors = ["Sergey Krifov <cr1phy@mail.ru>"]
description = "Городская торгово-экономическая симуляция"
repository = "https://github.com/username/cityrade"
license = "MIT"
readme = "README.md"

[workspace]
members = [".", "cityrade-types", "cityrade-macros"]
resolver = "2"

[profile.dev]
opt-level = 0
debug = true
lto = "off"

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
debug = false
strip = true
panic = "abort"

[profile.bench]
opt-level = 3
debug = false
lto = "thin"
strip = true
codegen-units = 1

[dependencies]
cityrade-types = { path = "cityrade-types" }
cityrade-macros = { path = "cityrade-macros" }
=======

[workspace]
members = [".", "cityrade-types", "cityrade-macros"]

[dependencies]
actix-web = { version = "4.10.2", features = ["macros"] }
actix-ws = "0.2.5"
tokio = { version = "1.44.1", features = ["macros", "rt-multi-thread", "time"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.134"
chrono = { version = "0.4.37", features = ["serde"] }
uuid = { version = "1.9.0", features = ["v4", "serde"] }
anyhow = "1.0.75"
cityrade-types = { path = "./cityrade-types" }
futures-util = "0.3.28"
rand = "0.8.5"
async-trait = "0.1.79"
clap = { version = "4.5.32", features = ["derive"] }

[lib]
name = "cityrade"
path = "src/lib.rs"

[[bin]]
name = "cityrade"
path = "src/main.rs"
>>>>>>> d7ffaf0 (initial)
